#!/bin/sh

brightness=$(/bin/cat /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/brightness)

if (($brightness > 0)); then
  let brightness=$brightness+100
  echo $brightness > /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/brightness
fi
